service:
  name: serverless-demo
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-scheduler

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: dev
  versionFunctions: false

functions:
  hello:
    handler: handler.hello
    events:
      # - http:
      #     method: get
      #     path: /{name}
      - schedule: rate(1 minute) # or cron syntax
